name: Build and Publish

on:
  - workflow_dispatch
  - workflow_call

jobs:
  linter:
    uses: ./.github/workflows/linter.yml

  build_sdist:
    needs: linter
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist .

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz

  publish_prod:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist
      
      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}